name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 修正：标签和标签用正确的YAML多行格式，变量语法符合metadata-action要求
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/cloudstream
          # tags规则：每行一个，用正确的YAML缩进
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=short
          # labels规则：每行一个键值对，变量用{{ .变量名 }}，确保YAML解析正确
          labels: |
            org.opencontainers.image.title=CloudStream
            org.opencontainers.image.description=CloudStream 云盘同步工具
            org.opencontainers.image.version={{ .Version }}
            org.opencontainers.image.revision={{ .Commit }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created={{ .Created }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
